### ISSUE TITLE
Set the folder name in the result zip

### ISSUE THREAD

**Issue by joeha480** [snaekobbi/pipeline-mod-mtm#7]
The base folder name in the zip should be settable.

**Comment by bertfrees** [comment]
See https://github.com/daisy/pipeline-issues/issues/434 and https://github.com/daisy/pipeline-framework/pull/71.

After this change you will be able to create your own subdirectory with your own name in the script, possibly settable with an option.

**Comment by bertfrees** [comment]
https://github.com/daisy/pipeline-issues/issues/434 has been fixed: that means that there is no base folder name called "pef-output-dir" in the ZIP anymore. After a change I'm about to commit, the base folder will be named to the identifier that has been passed as an option. However the ZIP file itself is still called "pef-output-dir.zip".

@BWestling is this acceptable?

**Comment by bertfrees** [comment]
Jens wrote:

> Regarding the output folders of a job in the MTM script: Would it be possible to have the output to look like: P00001\P00001.pef?
> At the moment it looks like this: results\output\pef-output-dir\P00001\P00001.pef
> All the best,
> Jens

**Comment by bertfrees** [comment]
@josteinaj Maybe you can shed some light on this because I'm a bit confused now. AFAIU, with https://github.com/daisy/pipeline-issues/issues/434 the result ZIP that comes from the engine does not include folders like "output-dir" anymore. I thought that I had even tested this, but now clearly the folders aren't gone yet. Did maybe something change in the web UI?

The "Download all results" button gives you a file named "results.zip" with the following content:

```
File
----------------------------------------
output/pef-output-dir/P00001/P00001.obfl
output/pef-output-dir/P00001/P00001.pef
```

Note that the OBFL file is present only when the "Include OBFL" option has been selected.

The "PEF" folder link below "Download all results" gives you a file named "pef-output-dir.zip" with the following content:

```
File
---------------------------------
pef-output-dir/P00001/P00001.obfl
pef-output-dir/P00001/P00001.pef
```

The "P00001.pef" and "P00001.obfl" file links below "PEF" give you the files directly.

The large "PEF" button in the middle gives you the same file as the "PEF" folder link below "Download all results" when "Include OBFL" is selected, or the file "P00001.pef" otherwise. 

I don't know how much of this is in your hands and how much depends on the engine, but I think this would be the ideal behavior:
- "Download all results"
  - with multiple output ports: result is zip named "results.zip", top level folders in zip are names of ports
  - with single output port
    - result has a single top-level file: result is file
    - result has a single top-level folder: result is zip named "&lt;folder&gt;.zip", no additional folders in zip
    - otherwise: result is zip named "&lt;port&gt;.zip", no additional folders in zip (or top level folder named "&lt;port&gt;"??)
- "PEF" (same behavior for big buttom in middle and link below "Download all results")
  - result has a single top-level file: result is file
  - result has a single top-level folder: result is zip named "&lt;folder&gt;.zip", no additional folders in zip
  - otherwise: result is zip named "pef-output-dir.zip", no additional folders in zip (or top level folder named "pef-output-dir"??)

**Comment by josteinaj** [comment]
For reference, here's the relevant Java code:
- [Web UI template decides whether to link to a single file or a zipped directory](https://github.com/daisy/pipeline-webui/blob/master/app/views/Jobs/getJob.scala.html#L317)
- [Web UI receives a request for results](https://github.com/daisy/pipeline-webui/blob/master/app/controllers/Jobs.java#L471)
- [Web API HTTP client library decides what to return](https://github.com/daisy/pipeline-clientlib-java/blob/master/clientlib-java-httpclient/src/main/java/org/daisy/pipeline/client/http/WS.java#L445)
- [Web API Job client library reads the relevant parts of the job XML](https://github.com/daisy/pipeline-clientlib-java/blob/master/clientlib-java/src/main/java/org/daisy/pipeline/client/models/Job.java#L91)

So, the current behavior for "Download all results" is to combine all output ports/options into one ZIP file, regardless of the number of options/ports and the number of files in each option/port. This mirrors the behavior of requesting the all results from the web API.

The behavior fror the big buttons on top are to download the file if there's only one file in the output, or the entire port or option if there's multiple files or directories in it.

What if we simply drop the "download all results" button? It doesn't really add any useful functionality I think.

If there's a single folder in a output directory I think the folder should be kept when downloading the zipped result. For instance, if there's a single directory called "P00001" then the script author intended that directory to be there.

**Comment by bertfrees** [comment]
Thanks for the explanation.

> What if we simply drop the "download all results" button? It doesn't really add any useful functionality I think.

I guess it would mean that script authors, if they want to provide the possibility to download all results with one button, need to put all the results on one port/option. Would that be OK? It would mean there is no possibility to download results separately except if you keep the links to the individual files in the web UI. One problem with this is that currently there are links to individual files but the folder structure is lost.

> If there's a single folder in a output directory I think the folder should be kept when downloading the zipped result. For instance, if there's a single directory called "P00001" then the script author intended that directory to be there.

Yes, that's what I suggested too (what I meant with no _additional_ folders).

**Comment by josteinaj** [comment]
> Yes, that's what I suggested too (what I meant with no additional folders).

Ok, maybe I misunderstood. I thought that for the links below "Download all results" you suggested that they should have the same behavior as for the big buttons? That would mean that if there's only one file in the result you would get that file instead of a directory + subdirectories with that file.

I don't know what the end-users prefer. In general we should probably avoid using the option names for folder names.

Another idea: If we want to be able to download everything at once (if end-users find that useful at all and not just confusing), then we could make the "Download all results" button merge all the option/ports into one directory - I doubt there will be any file naming conflicts and if there are then we can fall back to using either option names or option nicenames to create subdirectories.

I'm not 100% convinced about the usefulness of the file listing either by the way. We could actually eliminate the entire "Results" section if we wanted to simplify things. If we remove the file listing but keep the "Download all results" button then we could move the "Download all results" button up with the other buttons (right below them - and smaller):

![skjermbilde fra 2016-04-04 12-38-50](https://cloud.githubusercontent.com/assets/295481/14245524/473c1dd4-fa62-11e5-9cf6-d8cdf1eff232.png)

**Comment by bertfrees** [comment]
> I thought that for the links below "Download all results" you suggested that they should have the same behavior as for the big buttons? That would mean that if there's only one file in the result you would get that file instead of a directory + subdirectories with that file.

No I meant that both the big buttons in the middle and the links below "Download all results" should have the same behavior, but the behavior should be different from the current.

To make the "Download all results" button merge all the option/ports into one directory could be a good idea.

I know one use case where the file listing is useful, and that is to open the preview page, because "Forhåndsvisning" gives you a ZIP, while "foo.pef.html" opens directly in the browser. But I'm sure we can find a workaround for that, for example by moving the font file to somewhere online, or embedding it in the HTML file.

**Comment by josteinaj** [comment]
Yeah, that's useful, but it's not optimal. Ideally the "Forhåndsvisning"/"Preview" button should take you directly to the preview even if there are multiple files in the output directory.

One thing that has been discussed earlier is to have a "primary" output so that the jobs listing can have a single download link. Similarly we could possibly have a "primary" file in each output directory so that we could have a directory with multiple files but have the webui link to a single file.

Implementing something like that requires changes in the engine though. What we can do already is to create links in report documents. Maybe not as neat, but possible.

**Comment by bertfrees** [comment]
I don't understand "create links in report documents".

**Comment by josteinaj** [comment]
I mean that the report documents (`application/vnd.pipeline.reports+xml` or something) are rendered in the job view which means we can add links from those reports that open files in the results. It would be a bit awkward, but it would be possible. The links would be relative links on the form `<a href="result/option/[name]/idx/[name]/[filename]">Open preview</a>`. Anyway, I don't think it's a good solution - it feels a bit hackish. Just thought I'd mention it as a possibility.

**Comment by josteinaj** [comment]
For the case of previews (and any other HTML related views), we could have some special logic for filesets containing HTML:
- if there's exacly one HTML file in the fileset; link directly to that one
- if there's multiple HTML files and one of them is called `index.html`; link to that one
- otherwise link to the ZIPped version

**Comment by bertfrees** [comment]
Yes, sounds good, I think.

**Comment by josteinaj** [comment]
Ok, so then:
- handle filesets with HTML as above
- move "download all results" button to the other buttons above
- merge the contents of all output dirs in "download all results"
- remove "results" section including the file listing

Is that ok?

**Comment by bertfrees** [comment]
OK :+1:. And what about the "pef-output-dir" folder in the ZIP when you press the "PEF" button?

**Comment by josteinaj** [comment]
Right, that has to be removed as well.

**Comment by josteinaj** [comment]
Created webui issues now. Here they are:
- daisy/pipeline-webui#85
- daisy/pipeline-webui#86
- daisy/pipeline-webui#87

**Comment by bertfrees** [comment]
Great!

**Comment by bertfrees** [comment]
Should be fixed now, see https://github.com/daisy/pipeline-webui/issues/85.
